Vagrant.configure("2") do |config|

    config.vm.define "master" do |config|
        config.vm.box = "hashicorp/bionic64"
        config.vm.hostname = "master"
        config.vm.provision :shell, path: "docker_install.sh"
        config.vm.network "private_network", ip: "172.28.128.2"
    end

    config.vm.define "worker1" do |config|
        config.vm.box = "hashicorp/bionic64"
        config.vm.hostname = "worker1"
        config.vm.provision :shell, path: "docker_install.sh"
        config.vm.network "private_network", ip: "172.28.128.3"
    end

    config.vm.define "worker2" do |config|
        config.vm.box = "hashicorp/bionic64"
        config.vm.hostname = "worker2"
        config.vm.provision :shell, path: "docker_install.sh"
        config.vm.network "private_network", ip: "172.28.128.4"
    end
end